# Generated by Django 3.2.7 on 2021-09-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoAPI', '0002_todo_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='checked',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
